import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Experience from '../components/Experience'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Projects from '../components/Projects'
import Skills from '../components/Skills'

const Home: NextPage = () => {
    return (
        <div className="bg-[rgb(36,36,36)] text-white h-screen snap snap-mandatory overflow-scroll z-0">
            <Head>
                <title>Jeff Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <section id="hero" className="snap-center">
                <Hero />
            </section>

            {/* about */}
            <section id="about" className="snap-start">
                <About />
            </section>
            {/* Experience */}
            <section id="experience" className="snap-center">
                <Experience />
            </section>

            {/* skills */}
            <section id="skills" className="snap-start">
                <Skills />
            </section>

            {/* project */}
            <section id="projects">
                <Projects />
            </section>

            {/* contact me */}
        </div>
    )
}

export default Home

